# Generated by Django 4.2.4 on 2023-08-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='id_no',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='username',
        ),
    ]
