# Generated by Django 4.2.4 on 2023-08-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0002_rename_first_name_register_id_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='id_no',
            new_name='idNo',
        ),
    ]
