# Generated by Django 4.2.4 on 2023-08-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_rename_id_no_register_idno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='idNo',
        ),
    ]
