# Generated by Django 4.2.4 on 2023-08-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_customuser_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='id_no',
        ),
    ]
