# Generated by Django 4.2.4 on 2023-08-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0006_rename_username_login_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirm_password',
        ),
    ]
