# Generated by Django 4.2.4 on 2023-08-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0008_delete_login_remove_customuser_username_and_more'),
    ]

    operations = [
    ]
