# Generated by Django 4.2.4 on 2023-08-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0009_auto_20230827_0647'),
    ]

    operations = [
    ]
