# Generated by Django 4.2.4 on 2023-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0010_auto_20230827_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'logins',
                'db_table': 'login',
                'managed': True,
            },
        ),
    ]
