# Generated by Django 4.2.4 on 2023-08-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0011_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
